### ISSUE TITLE
Unable to open slave

### ISSUE THREAD

**Issue by TCMOOO** [RustAudio/cpal#249]
Could not open slave and resulted in thread panic. Installed pulseaudio-alsa package on Arch Linux to solve problem.

**Comment by taahamahdi** [comment]
In case you aren't on Arch Linux, all that package does is create the file `/etc/asound.conf` containing:
```bash
# Use PulseAudio by default
pcm.!default {
  type pulse
  fallback "sysdefault"
  hint {
    show on
    description "Default ALSA Output (currently PulseAudio Sound Server)"
  }
}

ctl.!default {
  type pulse
  fallback "sysdefault"
}

# vim:set ft=alsaconf:
```
