### ISSUE TITLE
UnknownTypeBuffer does not feel rusty

### ISSUE THREAD

**Issue by MOZGIII** [RustAudio/cpal#260]
I'm new to rust, but `UnknownTypeOutputBuffer`/`UnknownTypeInputBuffer` in the event loop API does not feel rusty at all.

I think it could be implemented differently, for example using traits with bound types.

After playing around a bit, I was able to pin point my discomfort to the following problem: enum types are used for encoding type information, which breaks a lot of flexibility that rust provides. As I've seen in the cpal implementation itself, macros are used to build the `UnknownTypeBuffer` result types, which tells me something's definitely wrong.

I'd like to discuss possible ways of improving this API.
Disclaimer: I'm still learning though, so my suggestions may be horribly bad.

So, why enum types, when we could use traits with bound types?

**Comment by MOZGIII** [comment]
Here's a particularly problematic example of the API usage:

```rust
fn add_to_vec(buf: cpal::UnknownTypeInputBuffer, vec: &mut Vec<f32>) {
    match buf {
        cpal::UnknownTypeInputBuffer::U16(buffer) => {
            for sample in buffer.iter() {
                let sample = cpal::Sample::to_f32(sample);
                vec.push(sample);
            }
        }
        cpal::UnknownTypeInputBuffer::I16(buffer) => {
            for sample in buffer.iter() {
                let sample = cpal::Sample::to_f32(sample);
                vec.push(sample);
            }
        }
        cpal::UnknownTypeInputBuffer::F32(buffer) => {
            for sample in buffer.iter() {
                let sample = cpal::Sample::to_f32(sample);
                vec.push(sample);
            }
        }
    }
}
```

The problem is, I don't know really know how I want this code to look like. Initially I was thinking that instead of having a implementation with concrete types I'd want to implement some trait three times.

That said, it seems I can implement a layer of indirection atop of the whole event loop API to add the logic to apply stricter types. But with that, I'm a bit worried that being built on top of this enum-based thing the API won't be zero-cost.
Please note though - here I apply very similar actions for all buffers, but I don't assume that the API should imply that; on the contrary - I'd like to implement separate behavior for every "case". What is case here? I'd say handling a particular stream is it's own case, i.e. a case per `StreamId`. If we were to implement an API around that it could be possible to negotiate the format *and the proper handler for that format input/output buffer* upfront, upon the creation a stream. Then, assuming the `EventLoop.run` invokes the callback for a particular stream only with it's negotiated format, it'd be safe and much easier to work with the formats at the user level.

Actually, after all this deduction, I'm even more certain that this API is not designed for direct consumer use, and is very low-level on it's own. But, again, the problem is it still adds it's own abstractions which aren't zero-cost (enum types for example). In that sense, the API is somewhere in-between the low-level and zero-cost thing, and the higher level nice-to-use. `cpal`'s mission statement tells that it wants to be as low-level as possible - so maybe we should try go even further in that direction?

**Comment by MOZGIII** [comment]
One more thing. I think it's a very bad idea for the cpal to do the sample format conversion under the hood. This, if needed, has to be a concern of a higher level entity. We're already good in that area, but that's important to me.

**Comment by ishitatsuyuki** [comment]
I think this is covered in #119
