### ISSUE TITLE
Implement Copy for StreamId?

### ISSUE THREAD

**Issue by eugene2k** [RustAudio/cpal#262]
Currently `StreamId` implements `Clone` but not `Copy` and the `EventLoop` functions take the `StreamId` by value. This leads to some clunky code, when a `StreamId` is encapsulated in an `Option`. It would be nice to either have `StreamId` implement `Copy` or the `EventLoop` take a reference to `StreamId` (unless, maybe, when destroying a stream). I don't see any reasons not to do this, but I'm not too familiar with the innards of the crate.

Edit: Actually, passing by reference wouldn't remove the clunkiness in most cases, so Copy is preferable to me. I'm not really sure if passing by reference is needed here, unless StreamId becomes some big structure with a lot of data...

**Comment by mitchmindtree** [comment]
Closing as `StreamId` was removed from the CPAL API some time ago.
