### ISSUE TITLE
Proposal: migrate to Azure pipelines

### ISSUE THREAD

**Issue by ishitatsuyuki** [RustAudio/cpal#291]
The current CI environment has made me some frustration because:

- CircleCI's web UI is ridiculously slow and ugly.
- You have to navigate through multiple CIs to view all the results.

Azure pipelines, which is being adopted by the rust-lang infra team, has support for all three major platforms, and the UI works pretty good. I wonder if it's worth the effort of migrating?

Regarding configuration, I got this as a reference by asking in `#infra` at rust-lang Discord:

https://github.com/xi-editor/druid/blob/master/.azure-pipelines.yml

**Comment by ishitatsuyuki** [comment]
Current state of Azure pipelines: they have a macOS environment that comes with Android tools, but support of Rust is not included and there are large boilerplates involved with toolchain installation.

**Comment by ishitatsuyuki** [comment]
The templates posted recently on Reddit may help: https://github.com/crate-ci/azure-pipelines

**Comment by est31** [comment]
We ended up migrating to Github Actions: #335 , closing
