### ISSUE TITLE
Audio capture hangs on Windows 10

### ISSUE THREAD

**Issue by redbluescreen** [RustAudio/cpal#299]
I made a modified version of record.rs example: https://gist.github.com/redbluescreen/ac5f0b1dde5318134ec601bec8b81d1f
It makes the recording duration longer and prints out an increasing counter.

For me the counter often stops at random. It seems to be easier to reproduce while there's also music playing at the same time.
Debugger shows that it's hanging in src/host/wasapi/stream.rs wait_for_handle_signal at WaitForMultipleObjectsEx
I reproduced it on both cpal 0.10.0 and 0.9.0.
Windows version: Windows 10 1903

**Comment by SuperiorJT** [comment]
I'm getting a similar issue although I'm not sure if mine is caused similarly. I'm just printing out input stream data indefinitely but it will randomly stop for no reason. No error either. It just stops printing and I have to terminate it manually.

**Comment by ishitatsuyuki** [comment]
Reproduced this. I will investigate but no ETA.
