### ISSUE TITLE
error should cause panic/abort

### ISSUE THREAD

**Issue by derekdreery** [RustAudio/cpal#309]
https://github.com/tomaka/cpal/blob/a04d869eaa0790a739c6ebbe80aeee949e529060/src/host/alsa/mod.rs#L803

This should be a panic/abort, not an error. This is because if the user tries to carry on after this error then the counter will wrap around to 0 and begin overwriting existing channels, possibly leading to anything including UB.

It was a panic until the error refactoring in 0.9.

**Comment by mitchmindtree** [comment]
Thanks for the issue! I'd be happy to merge a PR for this.
