### ISSUE TITLE
Getting rid of mem::uninitialized

### ISSUE THREAD

**Issue by est31** [RustAudio/cpal#316]
I see some occurences of `mem::uninitialized` in the codebase. It would be better to replace them with 0 or `MaybeUninit` from the `maybe-uninit` crate.

- [x] alsa backend (#317)
- [x] coreaudio backend (#317)
- [x] wasapi backend (#364 / a7008b63a5a7067dc38aa23618e2e5db9adf60e4)

**Comment by ishitatsuyuki** [comment]
It's good to get rid of those since `uninitialized` is deprecated, although it's not an urgent thing because AFAIK all usages are sound (doesn't violate invariants).

**Comment by est31** [comment]
Well it will start warning on nightly once nightly switches to 1.39.

**Comment by est31** [comment]
Only the wasapi/windows backend remains. But it requires either #318 or someone with a Windows machine to test it.

**Comment by ishitatsuyuki** [comment]
Maybe wait a bit - I'm doing a lot of refractors in #301.

**Comment by est31** [comment]
@ishitatsuyuki oh I see. Yeah I guess we should wait.

**Comment by gentoid** [comment]
A volunteer with Win 10 machine here. Just ping me if some help with testing is needed

**Comment by est31** [comment]
With #364 merged, this issue is fixed. Thanks everyone!
