### ISSUE TITLE
Appveyor is broken

### ISSUE THREAD

**Issue by est31** [RustAudio/cpal#318]
It seems that since the ownership transfer, appveyor has been broken.

Since Aug 10, these errors are being returned by the webhook:

```
{"message":"PR and project repositories do not match."}
```

See also https://github.com/appveyor/ci/issues/449

Not sure how to fix this.

**Comment by est31** [comment]
We could maybe migrate to GitHub actions to mitigate this. It's enabled for the org, lewton uses it too. @luni-4 @ishitatsuyuki what do you think?

**Comment by ishitatsuyuki** [comment]
Yes please, I don't have time to work on that but I was also planning to move to GitHub Actions.

**Comment by Luni-4** [comment]
Yep, I agree. I can work on that, feel free to assign this task to me :)

**Comment by est31** [comment]
Thanks @Luni-4 for working on this!

As for the config files, I guess appveyor can be removed as it is broken anyway. I'd say the other two can be removed as well as long as their functionality is replaced by the github actions config file. If you want to replace all in one go it's okay, just as replacing appveyor only and then tackling the other CIs later on.

**Comment by ishitatsuyuki** [comment]
Thanks for working on this. Some things you’d want to keep a sight on:
- the circleci build files cover web platform, which might need some effort to set up.
- the Travis config contains an auto-publishing step for tags; you could keep that intact. If you are going to migrate it, ask @mitchmindtree to set the token.

**Comment by Luni-4** [comment]
> As for the config files, I guess appveyor can be removed as it is broken anyway. I'd say the other two can be removed as well as long as their functionality is replaced by the github actions config file. If you want to replace all in one go it's okay, just as replacing appveyor only and then tackling the other CIs later on.

I think I will remove them in one go then, thanks!

> the circleci build files cover web platform, which might need some effort to set up.

Ok, I will maintain that, thanks for the advice!

> the Travis config contains an auto-publishing step for tags; you could keep that intact. If you are going to migrate it, ask @mitchmindtree to set the token.

IIRC it already exists an action for this step, but I need to check out. I will ask for sure if I need some help, thanks :)
