### ISSUE TITLE
Create community space

### ISSUE THREAD

**Issue by MOZGIII** [RustAudio/cpal#325]
This is more of a thing for the whole RustAudio project, than for cpal itself.

I think we need some sort of a community space where we could talk. I'm thinking of something like a Discord or Slack, or maybe a forum-like solution, or a mailing list.

To give this proposal some action already, I'll start by posting this link to a Discord room - https://discord.gg/4bEfJwQ - so we can gather for initial meetup. We can further discuss what form of communication we want to use here, and there should be no problem for people to move over from that link to something we favor more.

**Comment by ishitatsuyuki** [comment]
RustAudio official Discord - https://discord.gg/b3hjnGw

**Comment by MOZGIII** [comment]
Great! Please add it to the https://github.com/RustAudio org description.

**Comment by mitchmindtree** [comment]
There's also the RustAudio discourse forum https://rust-audio.discourse.group/
