### ISSUE TITLE
Migrate from alsa-sys to alsa?

### ISSUE THREAD

**Issue by diwic** [RustAudio/cpal#346]
Hi, I'm the maintainer of the alsa crate, and I'm wondering if it would make sense for CPAL to depend on the alsa crate rather than the alsa-sys crate?

I'm not familiar with CPAL, but from a quick glance at the code in the hosts/alsa directory a lot of that code is just simple wrappers around alsa-lib object - which is exactly what the alsa crate already has, so probably the alsa backend in CPAL could be very much simplified if it were to use the alsa crate instead.

That said, I probably won't have time (nor sufficient knowledge of CPAL) to make that code myself, but I still wanted to raise the issue.

**Comment by est31** [comment]
Hi @diwic ! See #308 for some discussion on this question.

**Comment by mitchmindtree** [comment]
Closed via #386.
