### ISSUE TITLE
Beep example fails with "Error: The requested device is no longer available. For example, it has been unplugged"

### ISSUE THREAD

**Issue by Emiluren** [RustAudio/cpal#352]
I tried running `examples/beep.rs` but it seems to fail with the following messages:
```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Error: The requested device is no longer available. For example, it has been unplugged.```

**Comment by Emiluren** [comment]
Just to test I tried running it with a jack server running but then I got this message instead:
```Error: A backend-specific error has occurred: buffer time could not be set: Invalid argument

Caused by:
    A backend-specific error has occurred: buffer time could not be set: Invalid argument```

**Comment by Emiluren** [comment]
I wanted to clarify that this happens whenever I try to use the library. The beep example just happened to be a small one

**Comment by skhalymon** [comment]
Could we suppress output of this errors somehow?

**Comment by Emiluren** [comment]
@skhalymon what do you mean by "supress this error"? The library doesn't work for me. It's not like I get these messages and then everything goes on as it should.

**Comment by Emiluren** [comment]
I might try again later today though to see if things have changed

**Comment by Emiluren** [comment]
Ok I have tried running it again now and I am a bit confused. It works as expected on my desktop computer so that's good. On my laptop I still get the first error but if I start jack it works. I don't know why it tries to use jack though because I am not running with the jack feature or command line argument.

**Comment by Emiluren** [comment]
Ok, after some experimentation I found that I could make it use pulseaudio by running it with `pulse` as an argument. Now at least I get audio :smiley:. I still get the errors about jack though so I guess I understand skhalymon's comment about supressing the error message now.

I wonder why `cpal::default_host().default_output()` returns jack for me though. :thinking: 

I also get this message printed
`ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port`

**Comment by Emiluren** [comment]
Ok, I finally figured out what my problem was. I had an `~/.asoundrc` that set jack as my default output device.
