### ISSUE TITLE
Problem with playback under arch linux.

### ISSUE THREAD

**Issue by perlindgren** [RustAudio/cpal#369]
Hi

When trying out the latest master I get.

```
cargo run --example beep
warning: field is never used: `can_pause`
   --> src/host/alsa/mod.rs:501:5
    |
501 |     can_pause: bool,
    |     ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
     Running `target/debug/examples/beep`
Error: A backend-specific error has occurred: buffer time could not be set: Invalid argument
```
I'm on arch Linux using Jack, all packages recently updated and other sound applications (Jack, pulseaudio, alsa) works as expected.

```
cargo run --example enumerate
warning: field is never used: `can_pause`
   --> src/host/alsa/mod.rs:501:5
    |
501 |     can_pause: bool,
    |     ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

   Compiling cpal v0.11.0 (/home/pln/rust/adder/cpal)
    Finished dev [unoptimized + debuginfo] target(s) in 1.92s
     Running `target/debug/examples/enumerate`
Supported hosts:
  [Alsa]
Available hosts:
  [Alsa]
ALSA
  Default Input Device:
    Some("default")
  Default Output Device:
    Some("default")
  Devices: 
  1. "jack"
    Default input stream format:
      Format { channels: 2, sample_rate: SampleRate(44100), data_type: F32 }
    All supported input stream formats:
      1.1. SupportedFormat { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), data_type: F32 }
    Default output stream format:
      Format { channels: 2, sample_rate: SampleRate(44100), data_type: F32 }
    All supported output stream formats:
      1.1. SupportedFormat { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), data_type: F32 }
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
  2. "hdmi:CARD=HDMI,DEV=0"
Error: DeviceNotAvailable
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
```

I have a similar setup on my laptop, arch, Jack etc. And there it works, so either my setup is wrong, or I hit a bug in `cpal`.

Any thoughts/ideas. What to try next?

**Comment by mitchmindtree** [comment]
It seems the issue has something to do with the way we specify the desired buffer size on the ALSA backend.

The source of the error is [here](https://github.com/RustAudio/cpal/blob/5390c01641b75267ff295207cc247f4db3465cf5/src/host/alsa/mod.rs#L960).

Specifically, the call to [`snd_pcm_hw_params_set_buffer_time_near`](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m___h_w___params.html#ga3bc1b188576d6d2daae9c56024813d10).

**Comment by perlindgren** [comment]
Oki, but not sure what to do about it. Is there a problem with my underlying ALSA driver or is it to be considered a bug in `cpal`.

**Comment by alxdb** [comment]
I'm also having this issue, using arch linux and alsa -> pulseaudio -> jack with the use of cadence. same error.

**Comment by sniperrifle2004** [comment]
The [alsa documentation](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m___h_w___params.html#ga3bc1b188576d6d2daae9c56024813d10) suggests that the configuration space is empty. That seems odd for `buffer_time`. I would be interested to see the output of `aplay --dump-hw-params` for this device.

**Comment by alxdb** [comment]
just tried running `aplay --dump-hw-params` on my machine, it just hangs. Tried with jack both enabled and disabled.

**Comment by sniperrifle2004** [comment]
Its waiting for input. Unfortunately you can't actually just use that command bare to get the parameters. Try `aplay --dump-hw-params <some wav file>`. Sorry for the confusion. However I have since found out that this problem probably is (was?) actually a bug in `alsa-lib`: https://bbs.archlinux.org/viewtopic.php?pid=1870274#p1870274

**Comment by alxdb** [comment]
Here's a dump of running `aplay` with a wav file
```
Playing WAVE '/home/alxdb/music/rips/afx-analogue_bubblebath_3/audio_00.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
HW Params of device "default":
--------------------
ACCESS:  MMAP_INTERLEAVED MMAP_NONINTERLEAVED MMAP_COMPLEX RW_INTERLEAVED RW_NONINTERLEAVED
FORMAT:  S8 U8 S16_LE S16_BE U16_LE U16_BE S24_LE S24_BE U24_LE U24_BE S32_LE S32_BE U32_LE U32_BE FLOAT_LE FLOAT_BE FLOAT64_LE FLOAT64_BE MU_LAW A_LAW IMA_ADPCM S20_LE S20_BE U20_LE U20_BE S24_3LE S24_3BE U24_3LE U24_3BE S20_3LE S20_3BE U20_3LE U20_3BE S18_3LE S18_3BE U18_3LE U18_3BE
SUBFORMAT:  STD
SAMPLE_BITS: [4 64]
FRAME_BITS: [4 640000]
CHANNELS: [1 10000]
RATE: [4000 4294967295)
PERIOD_TIME: (2 349525500)
PERIOD_SIZE: (0 4294967295)
PERIOD_BYTES: (0 4294967295)
PERIODS: (0 4294967295]
BUFFER_TIME: [1 4294967295]
BUFFER_SIZE: [1 4294967294]
BUFFER_BYTES: [1 4294967295]
TICK_TIME: ALL
--------------------
```

**Comment by sniperrifle2004** [comment]
That looks fine actually. I actually went through the hoops to setup jack and try aplay myself. Now the problem it turns out is not actually with the `set_buffer_time_near` option, but with the fact that cpal does not also do a `set_period_size_near` afterwards (or before?). That leaves an invalid period size in the hardware parameters and that than causes the `invalid argument` error.

Now I am already firmly convinced that cpal should set a proper period size as well for different reasons, so this just adds to that.

**Comment by sniperrifle2004** [comment]
Well it looks like I was wrong. I don't know why exactly, but the problem actually really just occurs for the jack device, with the plug alsa type as a default device. The underlying device and the jack device directly work fine.

**Comment by est31** [comment]
9503ab729e2c9a3911fe39d706b16091041ac004
