### ISSUE TITLE
Change `Format` to something more suitable/flexible

### ISSUE THREAD

**Issue by mitchmindtree** [RustAudio/cpal#370]
It has always seemed a little odd to me to include the sample rate within the stream's "format" type. Fields like `channels` and `interleaved` make sense as these describe the arrangement/layout of the streams' buffers, but sample rate seems a little out of place in a `Format` type.

Some other more general/flexible names that come to mind:

- `StreamParams/Parameters` It seems PortAudio [use this](http://portaudio.com/docs/v19-doxydocs/structPaStreamParameters.html#aa1e80ac0551162fd091db8936ccbe9a0).
- `StreamDesc/Description`
- `StreamConfig/Configuration`

I quite like `StreamParams` and `StreamConfig`.

These more general names might also make more sense for potential future fields like `desired_buffer_len` or others we haven't considered just yet.

Perhaps we could keep `StreamFormat` around for grouping the `channels` and `interleaved` (#367) fields, and have `StreamFormat` as a field within `StreamParams`/`StreamConfig`?

**Comment by Ralith** [comment]
`StreamConfig` sounds nice to me too. Are there cases where channel count and interleaving are needed but sample rate is not? If not, factoring those into a dedicated structure doesn't seem beneficial.

**Comment by mitchmindtree** [comment]
Good point!

OK I'm thinking I'll do up a PR with the following name changes:

- `Shape` -> `StreamConfig` - The configuration input required to build a stream.
- `Format` -> `SupportedStreamConfig` - Describes a single supported stream configuration.
- `SupportedFormat` -> `SupportedStreamConfigs` - Describes a range of supported configurations.
- `Device::default_input/output_format` -> `Device::default_input/output_config`.
- `Device::supported_input/output_formats` -> `Device::supported_input/output_configs`.
- `Device::SupportedInput/OutputFormats` -> `Device::SupportedInput/OutputConfigs`.
- `SupportedFormatsError` -> `SupportedStreamConfigsError`
- `DefaultFormatError` -> `DefaultStreamConfigError`

The name `SupportedStreamConfigs` is a little iffy considering it is the same configuration over a range of sample rates, however I'm thinking we can leave this for a PR that addresses #368 and `SupportedStreamConfigs` is at least a slight improvement for now.

Feel free to add any suggestions/amendments! If there are no objections I'll go ahead and start working on this in the next day or two.

**Comment by Ralith** [comment]
> `SupportedStreamConfigs`

In the spirit of not having type names that differ by one letter at the very end, maybe `SupportedStreamConfigRange` or `...Set`?

**Comment by mitchmindtree** [comment]
Sure, `Range` sounds good to me :+1:

**Comment by mitchmindtree** [comment]
Okydoke, I've implemented the above changes in #371. I'll leave it open for a day or two to leave a little more time for feedback.
