### ISSUE TITLE
old alsa-sys is vendored

### ISSUE THREAD

**Issue by BartMassey** [RustAudio/cpal#377]
It looks like there's an out-of-date copy of `alsa-sys` in the `cpal` source: its `Cargo.toml` says it's 0.1.1. This is unfortunate, since current `midir` depends on 0.1.2 and I'd like to use them together. Building `cpal` against `alsa-sys` 0.1.2 seems to work ok.

Any advice?

**Comment by mitchmindtree** [comment]
Hi! Just wanted to notify you that a solution has been proposed at #386 :)

**Comment by BartMassey** [comment]
Sweet! Looks like it's going well. Thanks for the note.
