### ISSUE TITLE
frames per buffer?

### ISSUE THREAD

**Issue by dansgithubuser** [RustAudio/cpal#381]
In PortAudio, I can request a certain number of frames per buffer: http://portaudio.com/docs/v19-doxydocs/open_default_stream.html

Seems that cpal doesn't have a way to control this? Am I missing something? Are there plans to add this?

All the best,
Dan

**Comment by mitchmindtree** [comment]
Hi @dansgithubuser! You might be interested in tracking #205. I hope to get back to focusing on CPAL in the coming weeks.

**Comment by dansgithubuser** [comment]
Perfect, thanks!
