### ISSUE TITLE
Disable CircleCI

### ISSUE THREAD

**Issue by mitchmindtree** [RustAudio/cpal#392]
It looks like circle-ci is still enabled for the repository. It has recently started showing up as a build error on PRs again, even though the configuration was removed in favour of using github actions long ago.

@RustAudio/cpal-maintainers is anyone familiar with circle-ci that could possibly disable this? @tomaka I noticed there's a CircleCI deploy key under Settings / Deploy Keys - is it just a matter of removing this? Or is this used for something else?

**Comment by tomaka** [comment]
I just disabled it.
