### ISSUE TITLE
Cpal crates version (really 0.11.0 ?)

### ISSUE THREAD

**Issue by simdax** [RustAudio/cpal#400]
Very minor issue, but kind of strange

I'm on the WSL2 debian, using stable rustup toolchain.
Referencing cpal in cargo.toml with version 0.11.0, which seems the last one, I'm not able to rerun the beep example (in the examples folder).
After looking at the source, I see that the downloaded src from cargo are the not the last one (no StreamTraits e.g. )

Is it intended ? Is the git repo considered unstable compared with the crates ?

**Comment by est31** [comment]
git master has some changes that haven't made it into 0.11.0.

You'll need to use the beep example from commit fe9054f626b5bc466e3844f35b44476bfb614fb8 , not from master. [Link](https://github.com/RustAudio/cpal/blob/fe9054f626b5bc466e3844f35b44476bfb614fb8/examples/beep.rs).
