### ISSUE TITLE
MacOS: feedback example suffers from popping at higher sample rates

### ISSUE THREAD

**Issue by thavlik** [RustAudio/cpal#402]
OS: MacOS 10.15.4 (Catalina)
Audio interface: Presonus Quantum

I'm encountering an issue with the feedback example causing popping and cracking that affects all audio, system-wide. This only occurs at sample rates exceeding 48kHz and only on Mac - Windows does not suffer from this ailment.

**Comment by mitchmindtree** [comment]
Could you clarify whether or not this occurs with both debug (`cargo run --example feedback`) and release (`cargo run --release --example feedback`)?

If you still notice the crackling, can you try increasing the hard-coded latency value within the example to see if this improves behaviour at all? 

I think the proper approach to doing something like `feedback.rs` example is to solve #349, however the idea of providing the `feedback.rs` example is to at least demonstrate a possible workaround for the meantime with cpal's current API.

**Comment by thavlik** [comment]
Apparently reconnecting the device was all it took to fix it, because the unchanged example no runs, in debug, just fine. Prior to moving it over to a Windows machine I tried restarting, made sure CPU usage was low, increased latency, etc. I have no idea. Seems like it might have been one time glitch.
