### ISSUE TITLE
Cannot record using bluetooth headset. Any idea why?

### ISSUE THREAD

**Issue by hiteshjoshi** [RustAudio/cpal#403]
The recorder example works well for inbuild microphone in macos, but when I switch to bluetooth headsets the example crashes
```
Error: A backend-specific error has occurred: core foundation unexpectedly returned null string

Caused by:
    A backend-specific error has occurred: core foundation unexpectedly returned null string
```

Can someone suggest why?

**Comment by est31** [comment]
Sounds a bit like the issue fixed by #399 . Do you use latest master or the crates.io release?

**Comment by hiteshjoshi** [comment]
Yes, I used 0.11.0

**Comment by hiteshjoshi** [comment]
I used the package from git. It worked well. Thanks @est31 

I have another question. During the recording if I switch my input device is there any event that can be raised? If so, can you guide me how?

**Comment by hiteshjoshi** [comment]
I think I will need some other library for rescue. On mac this can be done through https://developer.apple.com/documentation/avfoundation/avaudiosession/responding_to_audio_session_route_changes

**Comment by mitchmindtree** [comment]
@hiteshjoshi having device connected/disconnected events of some sort is certainly a feature worth considering. Would you mind opening a new issue for this?

Going to close this issue in the meantime as its seems your original bug is fixed on master.

**Comment by mitchmindtree** [comment]
Ahh it seems there's already an issue open for device arrival/removal notification events at #373
