### ISSUE TITLE
Provide proper range of available sample rates in webaudio backend

### ISSUE THREAD

**Issue by mitchmindtree** [RustAudio/cpal#410]
Currently 44.1khz is hard-coded throughout the implementation. However, an inline comment mentions that browsers must support all sample rates from 8khz to 96khz.

**Comment by julientregoat** [comment]
this seems like a big task, but would be interested in contributing somehow if you can help break it down & are open to it. also, would you be open to supporting up to 192k?

**Comment by mitchmindtree** [comment]
Hi @julientregoat, thanks for offering to dive into this! I thought I'd go ahead and implement this today as I plan to move on to getting input stream support working but wanted to address this issue first. Please feel welcome to take a look at #415 and provide any feedback.

Re 192khz, I'm hesitant to support this as the webaudio spec seems to only require that webaudio implementers support 8khz to 96khz. I haven't looked into it too thoroughly, but I imagine there might be an API out there that allows for querying what the *actual* supported sample rates are (rather than just this minimum set). If so, and if the API is portable (implemented by all major webaudio hosts/browsers) a follow-up PR would be more than welcome!

**Comment by julientregoat** [comment]
Okay cool! will put a pin in this for later then :)
