### ISSUE TITLE
[Question] How can I convert F32 buffer to i16 buffer?

### ISSUE THREAD

**Issue by DuckerMan** [RustAudio/cpal#417]
Hi there. My microphone supports i16 buffer, and output supports `f32` buffer. How can I convert i16 buffer to F32 buffer?

**Comment by julientregoat** [comment]
The `Sample` trait implements conversion functions between all of the `SampleFormat`s. so if you import that trait into scope you should be able to call `to_f32` on your `i16` values

**Comment by DuckerMan** [comment]
Thanks!
