### ISSUE TITLE
Getting a 0db or default volume?

### ISSUE THREAD

**Issue by thorlucas** [RustAudio/cpal#424]
Hi,

Is there a standard way to get some default volume amplitude? Using maximums of the datatype is much much louder than, for example, music at max volume (which is expected). Is there some helper function that returns a "0db"?

I noticed that for f32 it's clipped to +-1.0 (I think?). Is the equivalent for u16 std::u16::MAX? Same for i16?

Thanks,

**Comment by Jengamon** [comment]
For silence,
u16 -> `u16::max_value() / 2`
i16 -> `0`
f32 -> `0.0`
