### ISSUE TITLE
Unexpected output — how are stereo channels handled in the out buffer iterators?

### ISSUE THREAD

**Issue by thorlucas** [RustAudio/cpal#427]
I'm getting an unexpected doubling of frequency on simple waves.

After digging around, I realized that there is only one output buffer which doesn't appear to distinguish between channels. I suspect that perhaps this doubling of frequency is due to the left and right channels. i.e., if for each elem in the output buffer I increase my time by one, and there are two entries in the output buffer (one for right, one for left channel), then my frequency will be doubled and my left and right channels will have a slight phase offset.

The docs don't seem to mention how the LR channels are handled in the output buffer. How should I handle this? Should it be explicitly mentioned in the docs somewhere?

Thanks,

**Comment by mitchmindtree** [comment]
Hi @thorlucas, thanks for the issue!

CPAL's API currently only supports [interleaved buffers](https://stackoverflow.com/questions/17879933/whats-the-interleaved-audio). See #367 for discussion around future plans for improved data layout handling.

Feel free to re-open this if those links don't answer your questions.
