### ISSUE TITLE
`cargo publish` github workflow action reports "you don't seem to be an owner"

### ISSUE THREAD

**Issue by mitchmindtree** [RustAudio/cpal#428]
Not sure if it is an error or not, but [it looks like](https://github.com/RustAudio/cpal/runs/757565350?check_suite_focus=true) the cratesio token has been revoked or expired. Just making a note to remember to look into this.

**Comment by est31** [comment]
For posterity, the error is (old CI logs are being deleted by Github):
```
error: api errors (status 200 OK): this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.
##[error]Process completed with exit code 1.
```
In [this](https://github.com/RustAudio/cpal/runs/709348011) run from May 26 on 5fa5ce593d3692b2ff16f9585681f75fb27d8943 it still worked:
```
error: api errors (status 200 OK): crate version `0.11.0` is already uploaded
```

**Comment by est31** [comment]
This is what it shows in the settings menu:

![Screenshot_20200709_063822](https://user-images.githubusercontent.com/8872119/86997660-e9d8ef00-c1ae-11ea-89e1-023b79c029fa.png)

So the *token* is still valid, but for some reason it thinks that the user is not authorized.

**Comment by est31** [comment]
When I'm trying to publish locally with my personal API keys, I'm getting the same error even though I'm in the same cpal maintainers team...

**Comment by est31** [comment]
Filed a bug on the crates.io repo: https://github.com/rust-lang/crates.io/issues/2617

It used to work, but is now broken, and nothing got changed on our end that I'm aware of.

**Comment by est31** [comment]
Yup it works now: https://github.com/RustAudio/cpal/runs/852842097

**Comment by est31** [comment]
(For the solution see https://github.com/rust-lang/crates.io/issues/2617#issuecomment-655922401 )
