### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by skomski** [RustAudio/cpal#429]
I am quite interested in using the no eventloop refactor. Do you have any ETA for a new release?

**Comment by mitchmindtree** [comment]
I think #401 is close to landing - seeing as it's a slightly breaking change, perhaps we land that first and then publish 0.12?

**Comment by MOZGIII** [comment]
It makes sense to just ship without waiting for #401:

- There's already a lot of things to reconsider with event-loop removal in the app architectures, no point in delaying that work further.
- `cpal` releases are that rare that you don't have to worry about shipping breaking changes too frequently.
- Those who could use a version from git are fine, but there are people that need cargo-published versions who are eager to try new cool stuff.

**Comment by est31** [comment]
People seem to be running into #398 even though it's fixed on master. I think we should be doing a release sooner rather than waiting for something. @mitchmindtree is it ok with you if we make a release?

**Comment by mitchmindtree** [comment]
Yes that sounds fine to me!

**Comment by est31** [comment]
Unable to publish the release on crates.io, see #428

No idea what went wrong.

**Comment by est31** [comment]
Aaand it's uploaded to crates.io. Thanks @jtgeibel ! https://crates.io/crates/cpal/0.12.0
