### ISSUE TITLE
[Alsa Host] Start threshold of 0

### ISSUE THREAD

**Issue by sniperrifle2004** [RustAudio/cpal#432]
I noticed that currently the start threshold is set to 0 frames:

https://github.com/RustAudio/cpal/blob/b177bcdf22be548763c6bab2ffc83415eb343151/src/host/alsa/mod.rs#L910

Now this doesn't seem like a good idea to me. I don't think this has well defined behaviour across devices and it also seems counter intuitive, to start recording/playing before there are any frames. For playback that threshold should probably be the buffer size, while for recording a single frame would work and the resulting semantics would be the same.

Using significantly less than the buffer size for playback could result in underruns (Which lead to all kinds of fun), though with the alsa host's current approach to buffering - "Just use whatever the device uses or well 100ms is okay I guess" - that can still happen for certain applications. Luckily #401 will change that). Now a period size (Or even a single frame) would also work, but it's risky. If an application relies on the buffer, because the source is bursting or can just about make the period time, not filling up the buffer before starting will result in underruns and no amount of changing the buffer size will fix that if the start_threshold is not appropriately set.

EDIT: The alsa pcm example uses a period less then a full buffer. I guess that would work as well.

**Comment by sniperrifle2004** [comment]
If the intention was to not start the stream until `pcm.start()`, then setting the start_threshold to a high value would be the better approach (That is what [latency.c](https://www.alsa-project.org/alsa-doc/alsa-lib/_2test_2latency_8c-example.html#a14) does) since that is well defined. However I believe setting a proper start_threshold would be better forgoing `pcm.start()`. Otherwise you will still have to ensure data is available deferring the call to `pcm.start()`.

**Comment by diwic** [comment]
> Now this doesn't seem like a good idea to me. 

It really is not. However, the exact behaviour should not vary between backends, so I haven't tried changing it, because I don't know how the other backends work.

 > The alsa pcm example uses a period less then a full buffer. 

Not an example from alsa-rs, I hope? The buffer should be completely full before starting, not one period less than a full buffer.

**Comment by sniperrifle2004** [comment]
> 
> Not an example from alsa-rs, I hope? The buffer should be completely full before starting, not one period less than a full buffer.

Actually yes. I'd say it's *the* example: https://docs.rs/alsa/0.4.2/alsa/pcm/index.html

I agree that a full buffer would be the only right choice in theory, but I wasn't able to trigger a problem with the nearly full buffer. As part of #433 I had trouble getting it to fail at all, but it turns out that the alsa plugins are very effective at masking underruns.

**Comment by diwic** [comment]
> Actually yes. I'd say it's the example: https://docs.rs/alsa/0.4.2/alsa/pcm/index.html

Ehm, must have been a mind glitch on my part. But as you say, it does not matter much in practice.

**Comment by est31** [comment]
9503ab729e2c9a3911fe39d706b16091041ac004
