### ISSUE TITLE
Tie the data callback and the error callbacks to the lifetime of device

### ISSUE THREAD

**Issue by MOZGIII** [RustAudio/cpal#434]
Currently `build_*_stream*`s (e.g. `build_output_stream`) are taking `data_callback` and `error_callback` that are both required to be `'static`. It would make sense to make them bound to the `Device` lifetime.
Is it possible?
It would greatly reduce the amounts of rework I'd have to conduct in my codebase.

**Comment by mitchmindtree** [comment]
This would certainly be nice. That said, we'd need some way to guarantee that the callbacks are cleaned up and will no longer be called following the call to `Device::drop` and I'd imagine this might be tricky.

**Comment by XBagon** [comment]
I also stumbled over this, I'll probably have to clone my whole sound generating struct to be able to move it into the `data_callback`, due to the static lifetime, which isn't optimal.

**Comment by Ralith** [comment]
Sending non-`'static` closures to another thread is difficult because it's hard to guarantee that the borrowed resources outlive the period in which the other thread might be running the closure. For example, what happens if the audio thread is half way through running the closure, and the thread owning the resources it borrows leaks the `Device` and terminates?

**Comment by XBagon** [comment]
I managed to do it in version `0.11` with the `event_loop`. Was something wrong before? Also would maybe a function that closes the stream and return the content, for example an `impl DataCallback` object, be an option?

**Comment by tuzz** [comment]
My expectation would be that the lifetime of the `data_callback` should be greater than or equal to that of the stream returned by the `build_output_stream` function. If the resulting `Stream` is dropped then doesn't that terminate the underlying thread, meaning that data the callback borrows could then be dropped? I'm not sure why the lifetime needs to match that of the device, or indeed be `'static` ?

**Comment by Ralith** [comment]
> If the resulting Stream is dropped then doesn't that terminate the underlying thread, meaning that data the callback borrows could then be dropped?

Rust cannot guarantee that `drop` is invoked.

**Comment by MOZGIII** [comment]
I think we should carry over the lifetime of the `Device` - maybe via `'device` or sth. However, it doesn't seem to be possible with the level of abstraction that `cpal` aims to be at, at least from what I've seen previously.
I guess this is a `wontfix`, is it?

**Comment by ishitatsuyuki** [comment]
Yeah, this is wontfix. If you stumble upon this, you should be able to make it work with some use of `Arc`. If it doesn't solve your problem, then you might want to open a new issue.
