### ISSUE TITLE
[asio] Asio does not work in Cpal 0.12.0 from crates.io

### ISSUE THREAD

**Issue by HEnquist** [RustAudio/cpal#450]
There seems to be an issue with the packaging of the asio-sys crate. When building a project that uses the Cpal crate from crates.io, it also downloads a quite outdated version of asio-sys from crates.io. It seems the version that is included in the cpal repository doesn't get included in the cpal crate. The result is that the build fails because the old asio-sys is missing things.
Shouldn't the asio-sys crate be broken out to a separate repo, with a proper version number?

**Comment by est31** [comment]
Means we'll have to do an update of the asio-sys crate.

**Comment by est31** [comment]
cc @mitchmindtree

**Comment by est31** [comment]
I can't publish an asio-sys update, only @mitchmindtree can, so we'll have to wait until they've got time.

**Comment by mitchmindtree** [comment]
Sorry about the wait! I didn't realise I was the only publisher of `asio-sys` - I've added the `rustaudio:cpal-maintainers` team as a cargo owner, so it should be possible for all CPAL maintainers to publish this crate.

**Comment by HEnquist** [comment]
Great! Thanks for looking in to this :)

**Comment by est31** [comment]
0.12.1 is out and should have the fix. Please test and report if it's broken!

**Comment by HEnquist** [comment]
Works now! Thanks!
