### ISSUE TITLE
[Wasapi] Support for exclusive mode?

### ISSUE THREAD

**Issue by HEnquist** [RustAudio/cpal#459]
Hi, 
I was playing with the idea of adding support for wasapi exklusive mode. Before I actually start doing anything, I would just like to discuss a little how that should be done (and if it should be done at all!).
Shared mode works fine for most things. But in my application it would be great to be able to change the sample rate of the device, without having to go to the control panel. As far as I know, this required exclusive mode.
So two questions:
- Is there an interest to include support for wasapi exclusive mode?
- If cpal were to get support for exclusive mode, should it then be a separate host, something like WasapiExclusive?

**Comment by HEnquist** [comment]
Very silent here.. Since there haven't been any responses I guess there isn't any interest in this. I'll close this issue and drop the idea.

**Comment by pavhofman** [comment]
I think the exclusive mode support would be extremely useful. Rust is often used for high-performance DSP and the shared mode is suboptimal in such case. Thanks a lot!
