### ISSUE TITLE
Buffer underrun when starting stream. ALSA stream not started correctly?

### ISSUE THREAD

**Issue by sadmac7000** [RustAudio/cpal#460]
I'm using the following test program:

```rust
use cpal::traits::*;

fn main() {
    let host = cpal::default_host();
    let device = host
        .default_output_device()
        .expect("Default output device required.");

    let config = device.default_output_config().unwrap();
    let err_fn = |err| eprintln!("an error occurred on the output audio stream: {}", err);
    let sample_format = config.sample_format();
    let sample_rate = config.sample_rate().0 as f32;
    let config = config.into();
    let mut sample_clock = 0f32;
    let next_value = move || {
        sample_clock = (sample_clock + 1.0) % sample_rate;
        (sample_clock * 440.0 * 2.0 * 3.141592 / sample_rate).sin()
    };

    fn write<T: cpal::Sample, C: Send + FnMut() -> f32 + 'static>(mut sampler: C) -> Box<dyn FnMut(&mut [T], &cpal::OutputCallbackInfo) + Send> {
        Box::new(move |data: &mut [T], _| {
            for sample in data.iter_mut() {
                *sample = T::from(&sampler());
            }
        })
    }

    let stream = match sample_format {
        cpal::SampleFormat::F32 => device.build_output_stream(&config, write::<f32, _>(next_value), err_fn),
        cpal::SampleFormat::I16 => device.build_output_stream(&config, write::<i16, _>(next_value), err_fn),
        cpal::SampleFormat::U16 => device.build_output_stream(&config, write::<u16, _>(next_value), err_fn),
    }.unwrap();

    stream.play().unwrap();
    std::thread::sleep(std::time::Duration::from_millis(1000));
}
```

This works fine on my laptop (Fedora 32) but when I try to use it on my Raspberry Pi 4 with Yocto installed I get:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BackendSpecific { err: BackendSpecificError { description: "ALSA function \'snd_pcm_start\' failed with error \'EPIPE: Broken pipe\'" } }', src/main.rs:28:18
```

From everything I can gather, this is because the buffer is supposed to be populated *before* the call to `snd_pcm_start`. This would mean we should be processing some output before the call to `handle.start()?` at src/host/alsa/mod.rs:215.

**Comment by robhardwick** [comment]
I'm having the same issue on my Raspberry Pi 4 using Raspbian. I've come up with a quick fix which is just to ignore buffer underrun errors when starting the stream: https://github.com/robhardwick/cpal/commit/64ab9fe72de15989c573ba9956966ce1fd43ed7e

However, I'm not sure what the underlying problem is or if my fix is correct. I'd appreciate if anyone more knowledgeable than me could chime in. @diwic?

**Comment by diwic** [comment]
@mitchmindtree I think we're all in agreement that this needs to change, but do you know how the other backends behave so we can have the same behaviour across the different backends?

**Comment by sadmac7000** [comment]
I seem to observe that this bug was fixed. Most likely due to https://github.com/RustAudio/cpal/commit/c349eb1477b7e49ba406e179eb3c4b04d7f80766
