### ISSUE TITLE
Method with_sample_rate uses max sample rate

### ISSUE THREAD

**Issue by AlexanderHarrison** [RustAudio/cpal#461]
Method with_sample_rate on SupportedStreamConfigRange does not use given sample rate, but the max sample rate instead.

**Comment by italic-r** [comment]
I also see this issue, and the linked patch does make cpal return a StreamConfig with the right sample rate, but I have not tested it with a stream yet.

Just chiming in to say I have come across this, too.

**Comment by mitchmindtree** [comment]
Thank you both! Closing now that #462 is merged.
