### ISSUE TITLE
cpal 0.12.1 does not seem to compile for ARM (armhf)

### ISSUE THREAD

**Issue by fhennig** [RustAudio/cpal#473]
I get the following error on a blank project with just `cpal` 0.12.1 as the only dependency:

```
   Compiling cpal v0.12.1
error[E0308]: mismatched types
   --> /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.12.1/src/host/alsa/mod.rs:906:59
    |
906 |         BufferSize::Fixed(v) => hw_params.set_buffer_size(v as i64)?,
    |                                                           ^^^^^^^^ expected `i32`, found `i64`
    |
help: you can convert an `i64` to `i32` and panic if the converted value wouldn't fit
    |
906 |         BufferSize::Fixed(v) => hw_params.set_buffer_size((v as i64).try_into().unwrap())?,
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `cpal`.
```

To reproduce:

Create a new directory, go inside and run `cargo init`.  Then add `cpal = "0.12.1"` to the dependencies. Then run `cargo build --target armv7-unknown-linux-gnueabihf`, the target is configured like this:

```
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = ["-L", "/usr/lib/arm-linux-gnueabihf", "-L", "/lib/arm-linux-gnueabihf"]
```
in `~/.cargo/config`.

I did install the alsa development files like this: `sudo apt install libasound2-dev:armhf`.

My regular `cargo build` runs fine.

If I install 0.11 instead it compiles too! So it must be a change in 0.12.1.

Really weird error, I'm sure I'm doing something wrong but I don't know what it could be

**Comment by Ralith** [comment]
Looks like a cpal bug to me--that `as i64` probably needs to be `as c_long` or something like that.

**Comment by fhennig** [comment]
I checked the code, and in the snippet that rust provides, a `alsa::pcm::Frames` has been replaced with `i64`.  This is the original line:

    BufferSize::Fixed(v) => hw_params.set_buffer_size(v as alsa::pcm::Frames)?

[src/alsa/mod.rs:L906](https://github.com/RustAudio/cpal/blob/master/src/host/alsa/mod.rs#L906)

So maybe it has something to do with `alsa::pcm::Frames`? I'm a bit new to rust so I'm not so sure what that means.

**Comment by HEnquist** [comment]
It's probably not an ARM issue, but a 32 vs 64 bit one. On a 64-bit system this should be an i64, but on a 32-bit it should be i32. The conversion to alsa::pcm::frames takes care of this, so it should probably be put back in.

**Comment by est31** [comment]
13.0 is out now.

In the long term it might be a good idea to add a 32 bit platform to the CI. PRs welcome!
