### ISSUE TITLE
Output fails on raspberry pi

### ISSUE THREAD

**Issue by HalfVoxel** [RustAudio/cpal#481]
Hi

I'm been trying to get this running on a raspberry pi 1 (via rodio, but I think the issue is in cpal).
It has worked reasonably well except for a tiiny patch I had to make to cpal (it assumed a 64-bit clong type, this seems to have already been fixed in the cpal master branch though) and that compilation takes literally 4 hours.
However, when I try to play a sound I encounter the error

```
thread '<unnamed>' panicked at 'build_output_stream failed with all supported formats: BackendSpecific { err: BackendSpecificError { description: "ALSA function \'snd_pcm_start\' failed with error \'EPIPE: Broken pipe\'" } }', /home/pi/.cargo/git/checkouts/rodio-6458f6e95b054746/3bc614f/src/stream.rs:184:22
```

Do you have any idea what this can mean and what I can do to solve it?

Playing sounds using e.g. the `test-speaker` command works fine and the program I'm using works fine on another computer.

**Comment by est31** [comment]
I'll close this in favour of https://github.com/RustAudio/rodio/issues/323 for now until it's determined to be a cpal bug.
