### ISSUE TITLE
Sound in feedback.rs example massaged too much

### ISSUE THREAD

**Issue by 9to1url** [RustAudio/cpal#494]
I tried feedback.rs, but found sound output from the recording massaged too much, not clear.

Could you advice why?

Also if able to separate the input_stream and output_stream to two Threads , so can get better result?

**Comment by mitchmindtree** [comment]
Thanks for the issue @9to1url!

Could you please elaborate on what you mean by "massaged"? If you could also share what platform and host you are using that would also be appreciated.

**Comment by Txuritan** [comment]
I'm not sure if this is the same thing, but I tried out the feedback example.

The output audio was quite high pitched and crunchy almost like the sound effects of an SNES.

I'm running on Windows 10 using version 0.6.2.

**Comment by 9to1url** [comment]
Yes,the issue is not at cpal, the issue is at I wrote the output to virtual
sound device, and then the device write the sound to sip phone. The output
of sip phone quality not good.
If I change the sound to mono, sip phone output is great now.
You can close the issue, thanks.

**Comment by mitchmindtree** [comment]
Going to close this as the original issue has been resolved, though @Txuritan feel free to open a new issue for the distortion you are hearing on Windows (if there isn't already one open).
