### ISSUE TITLE
Update coreaudio-rs version please

### ISSUE THREAD

**Issue by open-trade** [RustAudio/cpal#501]
The bindgen is too old, causing a lot of conflicts. So many guys report it, you never reply.

https://github.com/RustAudio/coreaudio-rs/issues/68
https://github.com/RustAudio/cpal/issues/383

**Comment by est31** [comment]
@open-trade PRs welcome!

**Comment by est31** [comment]
Would also be cool to update core-foundation-sys

**Comment by open-trade** [comment]
> @open-trade PRs welcome!

I can not update coreaudio-rs crate, this can only be done by the author.

**Comment by est31** [comment]
Wait, coreaudio-rs is the latest version. Nothing that cpal can do here, closing.

**Comment by open-trade** [comment]
> Wait, coreaudio-rs is the latest version. Nothing that cpal can do here, closing.

Update coreaudio-sys version in coreaudio-rs.

**Comment by open-trade** [comment]
then update coreauido-rs
