### ISSUE TITLE
Can't find documentation on Period Length of recordings.

### ISSUE THREAD

**Issue by JonasRSV** [RustAudio/cpal#510]
Hey, I would like to set the period length of my recordings - but the only parameters I find is sample-rate, buffer_size and channels. Is period length unsupported or have I missed something? :)

**Comment by JonasRSV** [comment]
Maybe what I am looking for is buffer_size?

**Comment by pietervandermeer** [comment]
These are stream buffer settings. The longer the buffers, the less chance of overruns or underruns. The total length of your recording is something that belongs to your application. Just use a vector to accumulate your recording, and wait until it hits a certain size (configured by you).

**Comment by JonasRSV** [comment]
Thank you :)
