### ISSUE TITLE
Android: Crash on host.default_output_device()

### ISSUE THREAD

**Issue by Wicpar** [RustAudio/cpal#511]
When I try and run the following code:
```rust
    #[no_mangle]
    pub extern "system" fn Java_com_generic_jni_test(env: JNIEnv, _class: JClass, _input: JString) -> jstring {
        android_logger::init_once(
            Config::default().with_min_level(Level::Trace),
        );
        fn sample_rate() -> Option<String> {
            let host = cpal::default_host();
            info!("Got Host");
            let device = host.default_output_device()?;
            info!("Got Device");
            Some(format!("{:?}", device.name()))
            // println!("Got Device");
            // let config = device.default_output_config().ok()?;
            // println!("Got Config");
            // Some(config.sample_rate().0.to_string())
        }
        let res = sample_rate();
        let output = env.new_string(format!("Sample Rate: {:?}", res)).expect("Couldn't create java string!");
        output.into_inner()
    }
```

I get;
```
...
I/test::jni: Got Host
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 25008 (wicpar.rusttest), pid 25008 (wicpar.rusttest)
```

**Comment by Wicpar** [comment]
It also crashes when i run the examples with cargo ak run

**Comment by Wicpar** [comment]
Be careful to use the jni dependency with `default-features = false`
It has the backtrace feature by default which apparently doesn't work on android.

**Comment by osoftware** [comment]
@Wicpar Could you elaborate how you fixed the issue?

**Comment by Wicpar** [comment]
Two things: 
- cpal uses oboe and it doesn' t work on android 11 due to stdlibc++ shenanigans. i made a fork with a direct aaudio binding. i don't know if i pushed the changes to github though.
- make sure the app has the audio recording permission.

**Comment by nikita-skobov** [comment]
@Wicpar Can you check if you still have that fork, and could you make it public? (is it these changes? https://github.com/katyo/oboe-rs/compare/master...Wicpar:master)

**Comment by Wicpar** [comment]
@nikita-skobov no i didn't push them. I changed (on my fork) cpal directly as oboe is a lost cause.
