### ISSUE TITLE
RUSTSEC-2020-0056: stdweb: stdweb is unmaintained

### ISSUE THREAD

**Issue by brightly-salty** [RustAudio/cpal#518]
The stdweb crate is unmaintained, as recorded by [this RustSec advisory](https://rustsec.org/advisories/RUSTSEC-2020-0056.html). Here is the [reference issue](https://github.com/koute/stdweb/issues/403). 

Maintained alternatives include wasm-bindgen, js-sys, and web-sys.

I'm willing to look into this and see how difficult it is. I'm also willing to attempt it and open a pull request if it would be accepted.

**Comment by mitchmindtree** [comment]
Thanks for letting us know and for opening this! A PR addressing this would be more than welcome :)

**Comment by brightly-salty** [comment]
Almost everything's done, but I'm having a bit of trouble with `emscripten::audio_callback_fn`. It needs to be a static closure (among [other things](https://docs.rs/wasm-bindgen/0.2.69/wasm_bindgen/closure/struct.Closure.html#method.wrap)) to be able to convert into Js Function, but currently it is taking variables from `Device::build_output_stream_raw()`. Any ideas on how to refactor it to make it work?

**Comment by qarmin** [comment]
Any update?
PR is almost 1 year old without any comments or reviews

**Comment by est31** [comment]
Yeah, seems stdweb is dead. It would be nice if someone could rebase the PR and file new one with the rebased PR (or @brightly-salty does it).

**Comment by brightly-salty** [comment]
sure, I can try. I don't think I was ever able to get that closure issue working though.
