### ISSUE TITLE
No input only with specific input devices?

### ISSUE THREAD

**Issue by XiNiHa** [RustAudio/cpal#542]
Platform: macOS 11.2(arm64)

The feedback example doesn't work with some devices.
I have tested the MacBook built-in mic and a mic attached on USB-C earbuds(Samsung bundle)
I guess it's a problem with permission. Any ideas to fix it?

**Comment by XiNiHa** [comment]
Nevermind, running it using the macOS vanilla terminal fixed the issue with a permission dialog popped.

**Comment by XiNiHa** [comment]
I guess it's an issue of VSCode. iTerm2 also worked

**Comment by Zajozor** [comment]
Ran into the same issue today. Recording input was pure 0's.

I can confirm the "fix" you mention.
Opening in iterm2/vanilla terminal seems to work fine - mic permission popup appears and the input is recorded correctly :)
