### ISSUE TITLE
Continue Recording while there is input coming from the mic?

### ISSUE THREAD

**Issue by jackpeters667** [RustAudio/cpal#576]
Do we have anything like this? Record for as long as someone speaks, save to file when a long enough pause is detected.. for instance in seconds?

**Comment by dheijl** [comment]
You could measure the RMS value for each second of recording while recording, and when the RMS value remains low enough for n successive seconds you can decide that you have detected a pause and save to file. That's probably what I would do.

**Comment by est31** [comment]
Speech detection is out of scope for the cpal library, but a rudimentary method has been mentioned by @dheijl .

**Comment by jackpeters667** [comment]
> You could measure the RMS value for each second of recording while recording, and when the RMS value remains low enough for n successive seconds you can decide that you have detected a pause and save to file. That's probably what I would do.

Understood. Would you be able me achieve that? I once did it in Java but I used an external library to. I want to do be involved in writing this one

**Comment by dheijl** [comment]
The following two examples from cpal and hound should get you going: https://github.com/RustAudio/cpal/blob/master/examples/record_wav.rs
https://github.com/ruuda/hound/blob/master/examples/rms.rs
