### ISSUE TITLE
Beep example panics

### ISSUE THREAD

**Issue by koalefant** [RustAudio/cpal#578]
```
Output device: default
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DeviceNotAvailable', examples/beep.rs:82:49
```
Platform: Arch with PulseAudio backend.
cpal version: b628b9d

**Comment by Mordanis** [comment]
Not sure if this is still active, but I ran into a similar panic. On my machine it looks like it was an issue with the default device being some weird (virtual?) device with basically arbitrary channels and sample rate. Fix was to choose pulseaudio as the device, which for the demo can be done with `beep pulse`

**Comment by koalefant** [comment]
Initial issue was an user error. I had an `~/.asoundrc` with a broken Jack configuration. My apologies.

**Comment by ishitatsuyuki** [comment]
Do you have any remaining issues? If not, I think this can be closed.
