### ISSUE TITLE
Deduplicate parking_lot dependency 

### ISSUE THREAD

**Issue by alice-i-cecile** [RustAudio/cpal#664]
The Cargo.toml depends on two different versions of parking_lot, depending on which platform is used.

If possible, these should be synchronized to 0.12.

This came up in the context of https://github.com/bevyengine/bevy/pull/3825. Over at Bevy, we rely on cpal and try to avoid duplicate versions of crates in our dependencies to improve compile speeds and executable size.

**Comment by est31** [comment]
PRs welcome!

**Comment by TimJentzsch** [comment]
For some reason I'm getting a 500 error when trying to view the diff, but I believe this has been fixed via #644.

**Comment by TimJentzsch** [comment]
(As far as I can see, this PR hasn't been released yet, so the issue on Bevy's side is not yet fixed)

**Comment by est31** [comment]
Yeah it seems the github account that made that PR was deleted and thus there are 500 errors. A new release would be good. Need to check whether it is a semver breaking one.
