### ISSUE TITLE
Get the actual size of `BufferSize::Default`

### ISSUE THREAD

**Issue by SeedyROM** [RustAudio/cpal#665]
I want to get the size of the default buffer before the callback get's run. Is this possible?

**Comment by tiagoernst** [comment]
Same here not sure how I can find my default buffer size

**Comment by SeedyROM** [comment]
So the tip I learned later on is that you simply can't. This was my approach to the problem! https://github.com/SeedyROM/mixie/blob/main/src/audio/system.rs#L110-L144

Advice from The Audio Programmer discord:
![image](https://i.imgur.com/XMTWdJ4.png)

**Comment by est31** [comment]
Closing as question answered.
