### ISSUE TITLE
Migrate from lazy_static to once_cell 

### ISSUE THREAD

**Issue by james7132** [RustAudio/cpal#670]
`lazy_static` involves macros, takes a bit longer to compile, and `once_cell` provides more flexible ways for lazy initialization, and is on the way to [being added to `std`](https://github.com/rust-lang/rust/issues/74465). Replace all usages of `lazy_static` with ` static VAR: Lazy<T>`.

One potential drawback is that `lazy_static` supports spin-waiting on the result, while `Lazy` doesn't. I don't think any of crate's usages are perf-bound by this though.

**Comment by est31** [comment]
PRs welcome!
