### ISSUE TITLE
Example that doesn't use the default output device.

### ISSUE THREAD

**Issue by l-jaynes** [RustAudio/cpal#675]
I am having a little trouble understanding how to set the output device to use to a non default PCM. For example if I wanted to output to a pcm named "l2ch2" how would I go about configuring that? Every example I see and the how to guide only use the default output. Thanks.

**Comment by w-ensink** [comment]
Something like this?
```rust
let host = cpal::default_host();
let device = host
    .output_devices()
    .expect("failed to find output devices")
    .find(|d| d.name() == "l2ch2")
    .expect("no output device with name 'l2ch2'");
```

**Comment by l-jaynes** [comment]
Thanks for the example! That worked great.
