### ISSUE TITLE
CPAL fails compliation with ASIO due to unresolved imports

### ISSUE THREAD

**Issue by kyragit** [RustAudio/cpal#703]
I can't compile CPAL with the ASIO feature enabled. It appears to be failing to find some types in the asio-sys crate for some reason. There are about 50 unresolved imports (below is just one). I'm using the latest version of CPAL and on windows 10. I've looked in my files to make sure the asio-sys files are all there, and they are.

```
error[E0433]: failed to resolve: could not find `AsioSampleType` in `sys`
   --> C:\Users\<redacted>\.cargo\git\checkouts\cpal-c2179e82da06da7e\8c31e90\src\host\asio\device.rs:208:14
    |
208 |         sys::AsioSampleType::ASIOSTInt16MSB => SampleFormat::I16,
    |              ^^^^^^^^^^^^^^ could not find `AsioSampleType` in `sys`
````

**Comment by kyragit** [comment]
Closing issue, I had just set up my environment variables wrong.

**Comment by wapordev** [comment]
> Closing issue, I had just set up my environment variables wrong.

please explain how, I am having the same issue, and not sure what I've done wrong.

**Comment by kyragit** [comment]
It's been over a year, so I can't at all remember. But I can tell you that I have the environment variable `CPAL_ASIO_DIR` (both user and system for some reason) pointing to my asio files, for me that is at C:\Users\<user>\Documents\asio\asiosdk_<version>. Hopefully this helps.

**Comment by wapordev** [comment]
After several hours I got it fixed by going into the toml of the repo I was trying to build that used cpal, and by someone's suggestion updated it to the latest version. Repo wasn't old either, but I will definitely remember to add "make sure it's not fixed in a later version" to my troubleshooting. Thanks for replying though, I appreciate it
