### ISSUE TITLE
Traits SizedSample and FromSample dont exist (or i can't find them) yet there are in the examples

### ISSUE THREAD

**Issue by SeenLenz** [RustAudio/cpal#708]
So im pretty new to rust andd low level audio development so this might be entirely my fault. But when trying to run the example the two above mentioned traits are missing, and i couldn't find any mention about them in the documentation or anywhere else.

How is this possible? do i need to specify a feature in cargo.toml? or is beep.rs simply not updated?

**Comment by est31** [comment]
The opposite is the case. Likely you look at the examples from the master branch, which is from after the migration to the dasp_sample crate, while the crates.io release still is before that migration. The migration has been merged but not yet been released. I recommend you to use the examples [as they were as of the last release](https://github.com/RustAudio/cpal/tree/1ac8f1549f41001acd0acef2be9214ab72e61d11).
