### ISSUE TITLE
How do I calculate hertz with cpal?

### ISSUE THREAD

**Issue by Norlock** [RustAudio/cpal#725]
I try to calculate the frequencies of cpal using the differences in + / - in values (that's a sine?). But it comes out way to high, so what am I missing? Maybe github is not the correct place for these kind of questions but I don't know where else I can reach out for questions regarding cpal.  

See frequencies being calculated here:
https://github.com/Norlock/sparticles/blob/input/src/frequency.rs

**Comment by kyragit** [comment]
Not a dev, but I do know a bit about sound engineering. Are you trying to measure it for a simple tone, or any arbitrary sample? Except for pure sine waves, all sounds have many different frequencies. Finding the fundamental of any given sample is actually rather difficult, and will probably involve some difficult math (Fourier Transform). Looking at your github project, it looks like you're trying to analyze more than simple sine waves. I'd recommend looking into the Fourier Transform, it allows you to decompose signals into their frequency combinations.

**Comment by Norlock** [comment]
Yes I have a solution https://github.com/Norlock/sparticles/blob/input/src/audio/channel.rs where i take a library that does FFT and plot it. But maybe if you know a lot about sound engineering, can I ask you some questions about calculating frequencies? Like is it possible to determine the highest frequency by using the two highest points returned by the FFT and interpolate the highest possible one? I'm trying to learn more about frequencies so I can use it to connect my animations to it.
