### ISSUE TITLE
Release asio-sys 0.2.1

### ISSUE THREAD

**Issue by fhennig** [RustAudio/cpal#728]
I've been trying to build with asio support, and came across ﻿#383. It looks like this should be fixed with the new `asio-sys` 0.2.1 which was made in June. But the update hasn't been released on [crates.io](https://crates.io/crates/asio-sys). Can you guys release it there?

**Comment by est31** [comment]
I've released 0.2.1 now. Thanks for notifying.

**Comment by fhennig** [comment]
Wow, that was quick! Thank you very much!
