### ISSUE TITLE
Capture desktop audio on linux

### ISSUE THREAD

**Issue by Fractal-Tess** [RustAudio/cpal#736]
Hey there,

Disclaimer: This is just a question and not an issue!

How would one go about capturing desktop audio from an output device using cpal?

**Comment by dheijl** [comment]
I mainly followed the examples when implementing it for swyh-rs:  https://github.com/dheijl/swyh-rs/blob/master/src/utils/audiodevices.rs.

**Comment by Fractal-Tess** [comment]
I happen to also have tried your project yesterday. But to no avail - the web audio stream is silent.

As far as I can tell, you are simply doing 

```rs
let default_host = cpal::default_host();
let device = host.default_output_device().unwrap();
let audio_cfg = device.default_output_config().unwrap();
if let cpal::SampleFormat::F32 = audio_cfg.sample_format() {
   device
       .build_input_stream(
           &audio_cfg.config(),
           move |data, _: &_| wave_reader::<f32>(data, &mut f32_samples, rms_sender.clone()),
           capture_err_fn,
       )
       .unwrap();
}
```

Is this supposed to capture the audio desktop audio? 
In my case, there is nothing.

I even tried recording to a wav file using this approach: Using a `build_input_stream` on the `default_output_device` with `default_config`.

I think I'm completely misunderstanding how to use the library - Do you mind giving me a few pointers?

**Comment by dheijl** [comment]
It does capture audio being played.
On Linux make sure that you enable the audio monitor with pavucontrol, and check that you are capturing the device that is playing audio, on windows check in the soundmixer that the audio device you are capturing is the one that is playing audio.

**Comment by Fractal-Tess** [comment]
Hey @dheijl,

I finally managed to get a desktop audio output recording with your method using pavucontrol.
The way I did it is by setting the desktop audio output device as the fallback here with this button:
![image](https://user-images.githubusercontent.com/75957529/208105037-ed61adec-8b2d-4051-add4-19a34a706aac.png)

Before that, it used to be the microphone of the digital camera, so I guess this is correct now.
Would you mind explaining what is happening here?

Cheers!

**Comment by dheijl** [comment]
I have to admit that I haven't the faintest idea what is really happening here, I just know how to make it work...

**Comment by Fractal-Tess** [comment]
> I have to admit that I haven't the faintest idea what is really happening here, I just know how to make it work...

Still, thank you for the advice!

**Comment by hgaiser** [comment]
I found this page wondering the exact same thing :). Setting the monitor as the default does work, but I was wondering if there's a way to make it work through code.

Do either of you happen to know by now what is happening, or how to circumvent it? I tried looking at `device.supported_output_configs()` instead of `device.default_output_config()`, but it seems to only define the ranges that are accepted.

**Comment by dheijl** [comment]
I haven't found anything in the rust ecosystem that allows one to **control** audio devices in a system-independent way (abstracting away asio/wasapi/coreaudio/jack/pulse/pipewire like CPAL does for using them) .

**Comment by hgaiser** [comment]
> I haven't found anything in the rust ecosystem that allows one to **control** audio devices in a system-independent way (abstracting away asio/wasapi/coreaudio/jack/pulse/pipewire like CPAL does for using them) .

Thank you for your reply. Just to clarify: by control you also mean selecting an input device? The `build_input_stream()` function doesn't appear to allow you to select a device, suggesting it can only build a stream around the default input device.

**Comment by dheijl** [comment]
I mean control as in add, remove, enable, disable...

build_input_stream() is a method on a device, so you can use it on any device.

**Comment by hgaiser** [comment]
> I mean control as in add, remove, enable, disable...
> 
> build_input_stream() is a method on a device, so you can use it on any device.

Hmm what I meant is that I can't make the selection that I do in `pavucontrol` through `cpal`. At least if I iterate over input devices ([`Host::input_devices`](https://docs.rs/cpal/latest/cpal/traits/trait.HostTrait.html#method.input_devices)) on my system, I get the following output:

```
Ok("jack")
Ok("pipewire")
Ok("pulse")
Ok("default")
Ok("sysdefault:CARD=Generic")
Ok("front:CARD=Generic,DEV=0")
Ok("surround40:CARD=Generic,DEV=0")
Ok("surround51:CARD=Generic,DEV=0")
Ok("surround71:CARD=Generic,DEV=0")
```

None of these seem to point to the "Monitor of ..." that I see in `pavucontrol`. Anyway, didn't mean to hijack a dead issue :). I will use the workaround @dheijl posted earlier and possibly investigate alternatives later. Thanks anyway for the feedback!
