### ISSUE TITLE
No input device in WASM

### ISSUE THREAD

**Issue by Sibleyras** [RustAudio/cpal#739]
default_output_device() consistently returns None in WASM. Is there a way to expose default microphone input stream to CPAL?

**Comment by heinzelotto** [comment]
Currently WASM audio input is not supported, see [here](https://github.com/RustAudio/cpal/blob/5ade4e39078d10f54fae12bbeb87c8421be95595/src/host/webaudio/mod.rs#L182). I also need this, but I'm unfamiliar with the APIs so unlikely to be able to implement this myself.
