### ISSUE TITLE
0.15 breaking changes

### ISSUE THREAD

**Issue by dheijl** [RustAudio/cpal#747]
Would it be possible to document the breaking changes in build_output_stream(), and especially in the sample format conversions caused by the switch to dasp?

For instance the syntax `Sample::from(&0.0)` for f32 no longer works, and no documentation how to replace it...

**Comment by est31** [comment]
For `Sample::from` you can use [`Sample::from_sample`](https://docs.rs/dasp_sample/latest/dasp_sample/trait.Sample.html#method.from_sample) instead. For other changes, you can look at the changes in the examples in commit 85d773d59f1725b25002c6f04aa2eb9b43a75b76 .

**Comment by dheijl** [comment]
Thanks!
