### ISSUE TITLE
Trying to compile for Android with flutter rust bridge crashes

### ISSUE THREAD

**Issue by tGrothmannFluffy** [RustAudio/cpal#752]
Hi there,

I am trying to use cpal with the [flutter rust bridge](https://github.com/fzyzcjy/flutter_rust_bridge) on Android.
(I'm new to both flutter and rust so this will likely just be user error.)

I created an [issue over at flutter_rust_bridge that describes it in more detail](https://github.com/fzyzcjy/flutter_rust_bridge/issues/1058) and [fzyzcjy](https://github.com/fzyzcjy) suggested to ask over here.

Do you have any idea what the reason for this issue might be?

**Comment by alexandru0-dev** [comment]
@est31 (sorry to tag you) I have the same issue and I found that the method `default_output_config()` generates a panic. 
Apparently, the method tries to make use of the android context which doesn't have. 

My current bypass is to make a `cpal::SupportedStreamConfig` with manually set attribues, tho is not obtimal.

Any idea on how to tackle this problem or somebody that could help?
