### ISSUE TITLE
Needing exact N values without data loss in callback

### ISSUE THREAD

**Issue by inf17101** [RustAudio/cpal#758]
Hello, 

When using thread sleep function like in your example file **"record_wav.rs"**, I do not get always the same amount of values in a buffer when using the following code snippet to store values inside a container. This is because of different scheduling on each platform and OS.

I need exactly 4 sec recording time each round (recording is done in a loop) for further machine learning processing. The audio container with the pushed values inside is forwarded to further preprocessing steps. Those steps need a static sized amount of input values.

`std::thread::sleep(std::time::Duration::from_secs(recording_time));`

```
fn write_input_data<T>(input: &[T], channels: u16, writer: &AudioDataHandle)
where
    T: cpal::Sample,
{
    if let Ok(mut guard) = writer.try_lock() {
        if let Some(clip) = guard.as_mut() {
            for frame in input.chunks_exact(channels.into()) {
                // channels are stored like R L R L ... only R (mono) is needed
                clip.samples.push(frame[0].to_f32());
            }
        }
    }
}
```

How can I read from the stream having always static size N of values inside the container I am storing the floats?
And how can I avoid data loss when not consuming all values of "input: &[T]" in the callback round?
I need only mono channel.

I need for example always 192000 values inside the container, one round with 192000 and the next one with for example 192548 is not valid for my machine learning input processing reqs.

Can you give me a hint how to use the lib correct to achieve my goal?

**Comment by dheijl** [comment]
Use multiple threads and channels and don't sleep at all. The receiver can read 192000 samples, process them and wait for the next 192000 to arrive on the channel. The calback just pushes samples on the channel as they arrive. That is what I would do.

**Comment by inf17101** [comment]
Okay I will try this. I am using already channels to separate reading in audio data from the stream from preprocessing and so on. 

The only thing I am wondering is: Is this input: &[T] cleared after every callback or are the new values just appended to that stream / buffer? 

If I consume in this callback round let's say values 1 2 3 from that buffer containing 1 2 3 4 5 values. Are value 4 and 5 then still available when the next callback round is executed? 
Meaning I consume then in next round 4 5 ... and more? 

Ok if the answer is no to my question then it means I have to implement the logic for having static sized audio vector by myself? The lib does not provide to do something like this (in pseudo code):

stream.get_next_audio_data(192000, block = True); 

And it blocks until it has the amount of values available.

**Comment by dheijl** [comment]
In the callback you just push all the samples on the writing end of the channel and wait for the next callback to arrive with new samples.
The thread with the receving end of the channel is then free to process the samples as needed. The channel will do any necessary buffering for you.

**Comment by inf17101** [comment]
Thank you for your reply.

I have tried out and I am fine with the design, but the callback is FnMut. How can I pass in a channel sender correctly? On my site it compiles but at runtime the channel is moved, called once or never because it gets out of scope after setting up and returning the created stream.

Could you give some short example?

**Comment by dheijl** [comment]
It's difficult to comment without seeing your actual code.

A couple of remarks:

- you can not let the stream go out of scope, it has to stay alive as long as you want to capture audio
- if you use crossbeam channels instead of Rust channels, you can clone them instead of moving them in function calls, and they 're far more flexible than the standard Rust channels

If you have a look at [swyh-rs](https://github.com/dheijl/swyh-rs) I think it does a lot of the things you want to do.
But don't expect to find highly idiomatic or clean Rust code because it was the first ever program I wrote in Rust, as I used it as a vehicle to learn Rust.  But it works well enough.

**Comment by inf17101** [comment]
Hi thanks your reply.
It works now, I have also get it work with rust build-in channels.

Issue can be closed!
