### ISSUE TITLE
How do I capture audio and visualize it?

### ISSUE THREAD

**Issue by 0x5066** [RustAudio/cpal#789]
Hi!
I'm in the middle of porting my [Winamp-like Visualizer](https://github.com/0x5066/PynampVis) ([here](https://github.com/0x5066/RustampVis)), and so far `cpal` seems to offer what I want, capturing audio and using a callback to run a specific function that does the processing, similar to here:

winamposc.py code snippet:
```
def draw_wave(indata, frames, time, status):
    global visualization_mode, ys, peak1

    mono_audio = indata[:, 0] + indata[:, 1] / 2
    oscaudio = mono_audio + 0.03
    length = len(mono_audio)
    leftaudio = indata[:, 0]
    rightaudio = indata[:, 1]

    length = len(xs)
    blocksize_ratio = int(args.blocksize / length)
    fft_size = blocksize_ratio*23
    ys = 16 // 2 * (1 - np.clip(gain * leftaudio[::blocksize_ratio] + 0.03, -1, 1)) # The entire thing gets converted into this array, which also drives the oscilloscope visualization
    ys = ys.astype(int)
    ...
    
with sd.InputStream(dtype='float32', callback=draw_wave, channels=2, blocksize=args.blocksize*2, latency=0, device=args.device):
    while running:
        ...
```

However, trying to skim the docs trying to find a similar setup, I've come up dry, and trying one of the examples has only resorted to errors, is there anything that I've missed or can someone point me to something that'd achieve what I want?

**Comment by dheijl** [comment]
Perhaps have a look at [swyh-rs](https://github.com/dheijl/swyh-rs), I believe it does something similar?

**Comment by 0x5066** [comment]
I don't think swyh-rs is what I'm looking for, since it seems to be more focused on streaming, whereas I want to capture audio (either system and/or microphone audio) and have it visualized in real-time, with nothing else going on in between.
You can try running winamposc.py (under Linux, you'll find not much success with it on Windows) to get an example of what's needed.

**Comment by dheijl** [comment]
I didn't mean that swyh-rs is what you need, just that you could have a look at how swyh-rs captures audio using cpal, to get you going.

**Comment by 0x5066** [comment]
Ah, sorry for the misunderstanding then, I'll have a look around!

**Comment by 0x5066** [comment]
Well I've figured it out myself, thanks anyway!
