### ISSUE TITLE
Assertion in WASAPI

### ISSUE THREAD

**Issue by ryanmcgrath** [RustAudio/cpal#796]
Hi there!

A group of us are using this in a desktop application and had a user come in experiencing a crash on this line:

https://github.com/RustAudio/cpal/blob/f063271c232a4447169376e0c2be0c8a50649985/src/host/wasapi/device.rs#L444

Does this _need_ to be an assert, or could it bubble an error up the result chain? I'm happy to PR any changes if they're useful - but moreso if I'm not missing any context as to why it is the way it is. :)

The application in question is a C++ base calling into Rust, so at the moment we set our builds to `panic='abort'`, which causes this to crash (and in `abort` behavior we're unable to `catch_unwind` this path of code). Our particular use case would be fine with no audio playing and just being able to detect and show an error to the user.

(If I'm off my rocker on the above please just let me know)

**Comment by est31** [comment]
Yeah this looks like something we should bubble up. Maybe a `BackendSpecificError` with a message along those lines?

**Comment by ryanmcgrath** [comment]
Closing since #797 was merged. Thanks!
