### ISSUE TITLE
migrate WASM example and documentation+Wiki from webpack to trunk

### ISSUE THREAD

**Issue by spookyvision** [RustAudio/cpal#834]
Out of curiosity, I tried migrating the WASM example to [trunk](https://trunkrs.dev/) and it worked out of the box. In my opinion this is much more straightforward (does not require any JavaScript nor `npm` and a big `node_modules` folder). Are you interested in this change? If yes, I'll create a PR.

**Comment by spookyvision** [comment]
another alternative would be [cargo-run-wasm](https://github.com/rukai/cargo-run-wasm), with which the example could be entirely self-contained (no external dependencies)

**Comment by est31** [comment]
Yeah I agree, trunk is way better than webpack for the reasons you stated.

**Comment by spookyvision** [comment]
I thought about it some more and I'd say trunk is preferable over cargo-run-wasm, since the latter is really only suitable for tiny examples (can't customize the HTML at all). I'll go ahead and send a trunk-based PR soon.
