### ISSUE TITLE
iOS randomly chooses speaker and earpiece

### ISSUE THREAD

**Issue by tGrothmannFluffy** [RustAudio/cpal#862]
Hi there,

after somewhat mitigating another ios issue (https://github.com/RustAudio/cpal/issues/842), I am still having trouble with the audio devices.

Whenever I open an audio output stream:
```rs
let host = cpal::default_host();
let device = host
    .default_output_device()
    .expect("no output device available");
let config = ...
device.build_output_stream(...
```
the iPhone seemingly randomly chooses between the built in earpiece and speaker. It isn't related to me holding it to my ear.

Is there a way to choose? I am only getting one audio output device ("Default Device") on the host...

**Comment by tGrothmannFluffy** [comment]
I might have found the solution by doing something like this in flutter:

```dart
Future<AudioSession> startAudioSession(bool microphone) async {
  var session = await AudioSession.instance;
  if (microphone) {
    await session.configure(const AudioSessionConfiguration.music().copyWith(
        avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
        avAudioSessionMode: AVAudioSessionMode.measurement));
  } else {
    await session.configure(const AudioSessionConfiguration.music().copyWith(
      avAudioSessionCategory: AVAudioSessionCategory.playback,
      avAudioSessionCategoryOptions: AVAudioSessionCategoryOptions.defaultToSpeaker &
          AVAudioSessionCategoryOptions.allowBluetooth &
          AVAudioSessionCategoryOptions.allowBluetoothA2dp &
          AVAudioSessionCategoryOptions.allowAirPlay &
          AVAudioSessionCategoryOptions.mixWithOthers &
          AVAudioSessionCategoryOptions.mixWithOthers,
      avAudioSessionMode: AVAudioSessionMode.measurement,
    ));
  }
  await session.setActive(true);
  return session;
}
```

**Comment by kevinkouketsu** [comment]
Can you provide some details? I am facing some issues with iOS. AudioSession is something from flutter?

**Comment by tGrothmannFluffy** [comment]
Audio Session is [a flutter pacakge](https://pub.dev/packages/audio_session), it can manage your iOS [AVAudioSession](https://developer.apple.com/documentation/avfaudio/avaudiosession). It seems like cpal fails to do so (I don't know if by design or not?), and you have to configure and start the audio session yourself.
