### ISSUE TITLE
ASIO4ALL.org looks... unsafe.

### ISSUE THREAD

**Issue by jacksonbrim** [RustAudio/cpal#883]
I visited ASIO4ALL to download the suggested ASIO driver per the crates.io instructions, and what I saw was a bit concerning.

Is ASIO4ALL.org really the best place you can download an ASIO audio driver?

I'm only posting this in the hopes that the site has been hacked and can be brought to someone's attention.

![Screenshot 2024-05-10 170442](https://github.com/RustAudio/cpal/assets/9915390/82f97d3d-7129-4eb1-89de-1cab04d3ebd9)

**Comment by est31** [comment]
It seems that the ads on that website are intrusive. If you have an adblocker, those weird sketchy download buttons are gone. Maybe try contacting the asio4all maintainer about this issue?

Otherwise open for suggestions for alternatives of asio4all.

**Comment by YPares** [comment]
Yeah it's a pretty odd and old-looking site, but it's legit, a lot of audio producers on Windows actually use Asio4All, which in the case of some audio interfaces can provide better Asio support than the official audio interface drivers.

**Comment by jacksonbrim** [comment]
I'm really just trying to use CPAL to get audio input from a microphone on windows, and then process / visualize it.

I had used cpal to play some frequencies recently, and figured it'd be a good choice since it had the functionality.

Would cpal be the best option for this if I'm not able to use this Asio driver? I'm afraid I'm not brave enough to download one from the Asio4All website.
