### ISSUE TITLE
How many output streams is good practice?

### ISSUE THREAD

**Issue by nrawrx3** [RustAudio/cpal#925]
Being new to audio programming, I need to know if I should be creating

1. Multiple device objects and create one output stream for each - use case being VoIP chat and streaming audio - where each stream corresponds to a single participant. This approach does not feel very scalable of course. 

2. One device with multiple streams - each stream still concerned with exactly one participant.

3. Or am I better off using/implementing a mixer and output the mixed sound into a single devices' single output stream?

**Comment by Ralith** [comment]
Typically you'd use a single stream and do your own mixing.
