### ISSUE TITLE
Support for android

### ISSUE THREAD

**Issue by tomaka** [RustAudio/cpal#93]

**Comment by Xaeroxe** [comment]
@tomaka if you haven't gotten around to this within approximately a few months the Amethyst team will likely try and complete this for you, since Android support is on our upcoming priority list.

**Comment by tomaka** [comment]
@Xaeroxe That would be nice! It shouldn't be *too* hard to do.

**Comment by alanpoon** [comment]
I have been trying work on this issue using opensles-sys. But i am stuck. 
[https://github.com/AmpMe/opensles-sys/issues/4](url)
Would appreciate if there is someone who can guide me.

**Comment by Sach97** [comment]
From the android [docs](https://source.android.com/devices/audio) they suggest the HAL interface which native librairies are [audio_hw.c](https://android.googlesource.com/platform/hardware/libhardware/+/master/modules/audio/audio_hw.c), [audio_policy.c](https://android.googlesource.com/platform/hardware/libhardware/+/master/modules/audio/audio_policy.c) and the headers [audio.h](https://android.googlesource.com/platform/hardware/libhardware/+/master/include/hardware/audio.h). Is it what we are looking for this feature ?

**Comment by msiglreith** [comment]
A basic implementation which could be used as basis using OpenSLES: https://github.com/norse-rs/audir/blob/master/src/opensles/mod.rs
AAudio would be also interesting due to being a newer API but also less widespread support.

(I would be interested in staring with a `cpal` backend but would like to do some general API changes beforehand 👀 )

**Comment by ishitatsuyuki** [comment]
FYI, [Oboe](https://github.com/google/oboe) is an official library that wraps both.

**Comment by blainekasten** [comment]
Oboe has a rust interface here: https://docs.rs/oboe/0.1.0/oboe/

Would be reallllyyyyyy great if android was supported.

**Comment by repi** [comment]
Anyone been looking into Android support further? We (Embark) are interested in having it

**Comment by alisomay** [comment]
Android support +1

**Comment by tom-bowles** [comment]
Closed by #468?
