### ISSUE TITLE
`build_input_stream`: What does `data` store?

### ISSUE THREAD

**Issue by TornaxO7** [RustAudio/cpal#932]
Hi! I've got a question regarding [`build_input_stream`](https://docs.rs/cpal/0.15.3/cpal/traits/trait.DeviceTrait.html#method.build_input_stream) and its `data_callback` argument: What does the first argument hold? In my case, they are `F32` values but the array has a length of 3700. What does each value represent?

**Comment by TornaxO7** [comment]
Ok, one person on discord helped me with this. If we're understanding it correctly, `data` basically holds a snapshot of the audio otherwise it would call the provided function "everytime" for each new sound, which may have a bad performance (or other reasons). So it's using its internal buffer and waits a specifique amount of time until it's full and then calls the provided function with the filled part of the buffer while (another?) buffer gets filled up and so on. I hope that's roughly correct.

**Comment by Hifive55555** [comment]
@TornaxO7 I used to think that data represents a buffer with a length of buffer_size * num_channels which you can iter each frame by data.chunks_mut(num_channels). This did work. However, I print the length of data, and it differs from the buffer_size * num_channels in `StreamConfig` used to build the stream. I am confused of that.

**Comment by Ralith** [comment]
Some backends don't respect the configured buffer size, and may even vary buffer size dynamically.
